/**
 * Game Data Types - Core data structures
 */

import type {
  CustomTask,
  MainQuest,
  Season,
  Category,
  RecurringTask,
  ArchivedTask,
  TaskLog,
  WeeklyGoal,
  Habit,
  RewardSticker,
} from './task';
import type { GameEvent, EventMemories } from './event';

/**
 * Player Stats
 */
export interface PlayerStats {
  life: number;
  intelligence: number;
  spirit: number;
  action: number;
  agility: number;
  charm: number;
}

/**
 * Daily Tasks (checkboxes)
 */
export interface DailyTasks {
  shutdown: boolean;
  laugh: boolean;
  vision: boolean;
  walk: boolean;
  signal: boolean;
  log: boolean;
}

/**
 * Skill Entry
 */
export interface SkillEntry {
  level: number;
  xp: number;
  maxXp: number;
}

/**
 * Skills Structure
 */
export interface Skills {
  magician: {
    manifestation: SkillEntry;
    beliefAlignment: SkillEntry;
    energyAlchemy: SkillEntry;
  };
  systemBalancer: {
    teaming: SkillEntry;
    karmaManagement: SkillEntry;
    startupAlchemy: SkillEntry;
  };
  observer: {
    intuitionNavigation: SkillEntry;
    selfCompassion: SkillEntry;
    tripleVision: SkillEntry;
  };
}

export type BeliefSystemMode = 'default' | 'profile';

export interface BeliefSystemConfig {
  mode: BeliefSystemMode;
  profileBeliefs: string[];
}

export interface LoreProfile {
  worldTheme: string;
  playerArchetype: string;
  taboos: string[];
  preferredTone: 'epic' | 'grounded' | 'playful';
  freeTextLore: string;
  version: number;
}

export interface WorldFaction {
  id: string;
  name: string;
  stance: number; // -100 ~ 100
  influence: number; // 0 ~ 100
}

export interface WorldEvent {
  id: string;
  title: string;
  severity: 'low' | 'medium' | 'high';
  startedAt: string;
  expiresAt?: string;
}

export interface WorldState {
  epoch: number;
  factions: WorldFaction[];
  worldVariables: Record<string, number | string | boolean>;
  activeWorldEvents: WorldEvent[];
  lastEvolutionAt: string;
}

export interface ProgressionRule {
  primarySkills: string[];
  secondarySkills: string[];
  attributeWeights: Record<string, number>;
}

export interface ProgressionConfig {
  taskTypeRules: Record<'creative' | 'tax' | 'maintenance', ProgressionRule>;
  aiAdjustmentBounds: {
    min: number;
    max: number;
  };
  periodCaps: {
    dailySkillXpCap: number;
    weeklySkillXpCap: number;
    dailyAttrCap: number;
  };
}

export interface GeneratedTitleEntry {
  id: string;
  name: string;
  description: string;
  rarity: 'C' | 'B' | 'A' | 'S';
  sourceType: 'season' | 'chapter' | 'quest' | 'system';
  sourceId: string;
  unlockedAt: string;
  autoGenerated: boolean;
}

export interface TitleUnlockHistoryEntry {
  titleId: string;
  reason: string;
  timestamp: string;
}

export interface TitleCatalog {
  generatedTitles: GeneratedTitleEntry[];
  unlockHistory: TitleUnlockHistoryEntry[];
}

export interface OrchestrationLogEntry {
  id: string;
  trigger: 'quest_completed' | 'daily_review_saved' | 'weekly_review_saved' | 'manual';
  timestamp: string;
  inputSummary: string;
  proposals: string[];
  autoActions: string[];
  pendingConfirmations: string[];
  rolledBack: boolean;
}

/**
 * Pomodoro State
 */
export interface PomodoroData {
  completedToday: number;
  lastPomodoroDate: string;
  totalCompleted: number;
  lastUsedTaskId: string | null;
}

/**
 * Resource - Time
 */
export interface TimeResource {
  total: number; // Total accumulated minutes
}

/**
 * Resource - Money
 */
export interface MoneyResource {
  balance: number;
  monthlyIncome: number;
  monthlyBudget: number;
  monthlySpent: number;
  monthlyNet: number;
  currentMonth: string; // YYYY-MM format
}

/**
 * Sleep Record
 */
export interface SleepRecord {
  date: string;
  bedTime: string;
  wakeTime: string;
  quality: number;
  duration: number;
  notes?: string;
  aiAnalysis?: string;
}

/**
 * Resource - Energy
 */
export interface EnergyResource {
  current: number; // 0-100
  lastUpdate: string;
  lastSleepRecord: SleepRecord | null;
}

/**
 * Resources
 */
export interface Resources {
  time: TimeResource;
  money: MoneyResource;
  energy: EnergyResource;
}

/**
 * Financial Record
 */
export interface FinancialRecord {
  id: string;
  type: 'income' | 'expense';
  amount: number;
  category: string;
  source?: 'manual' | 'reward_redeem' | 'system' | 'ai';
  relatedEntityType?: 'reward' | 'task';
  relatedEntityId?: string;
  description?: string;
  date: string;
}

/**
 * Journal Entry
 */
export interface JournalEntry {
  id: string;
  content: string;
  mood?: string;
  tags?: string[];
  aiAnalysis?: string;
  createdAt: string;
}

/**
 * Resource Log
 */
export interface ResourceLog {
  id: string;
  resourceType: 'time' | 'money' | 'energy';
  change: number;
  reason: string;
  timestamp: string;
}

export interface RewardActionLog {
  id: string;
  text: string;
  timestamp: string;
}

export interface RewardPricingConfig {
  eat: number;
  drink: number;
  buy: number;
  watch: number;
  play: number;
  rest: number;
  other: number;
}

export interface DailyCompletionSnapshot {
  date: string; // YYYY-MM-DD
  tasksCompleted: number;
  tasksCreated: number;
  completionRate: number;
  frozenAt: string;
  source: 'event_rebuild' | 'fallback';
}

/**
 * Energy History Entry
 */
export interface EnergyHistoryEntry {
  date: string;
  levels: number[];
  average: number;
}

/**
 * Title Entry
 */
export interface Title {
  id: string;
  name: string;
  type: 'level' | 'achievement' | 'special';
  minLevel?: number;
  condition?: string;
  description: string;
}

/**
 * Transmigration Data (cross-season inheritance)
 */
export interface Transmigration {
  permanentTitles: string[];
  keyItems: string[];
  unlockedSeasons: string[];
  unlockedDungeons: string[];
  totalLifetimeXP: number;
}

/**
 * Monitor Settings
 */
export interface MonitorSettings {
  enabled: boolean;
  chartRange: 7 | 30 | 90;
  alertsEnabled: boolean;
  lastDailyReport: string | null;
  reportTime: number; // 0-23
  deadlineAlertTimes: number[];
}

/**
 * Questionnaire History
 */
export interface QuestionnaireHistory {
  history: Array<{
    id: string;
    type: string;
    responses: Record<string, unknown>;
    completedAt: string;
  }>;
  statistics: Record<string, unknown>;
  settings: Record<string, unknown>;
}

/**
 * Saved Rewards
 */
export interface SavedRewards {
  quotes: string[];
  knowledge: string[];
  trivia: string[];
  jokes: string[];
  memes: string[];
}

/**
 * AI Analysis History Entry
 */
export interface AIAnalysisEntry {
  id: string;
  taskId?: string;
  analysis: Record<string, unknown>;
  timestamp: string;
}

/**
 * Complete Game Data Structure
 */
export interface GameData {
  // Player attributes
  stats: PlayerStats;
  level: number;
  experience: number;
  currentTitle: string;
  unlockedTitles: string[];

  // Daily tasks
  dailyTasks: DailyTasks;
  lastReset: string;
  dailyCareCompleted: boolean;

  // Custom tasks
  customTasks: CustomTask[];
  archivedTasks: ArchivedTask[];

  // Main quests
  mainQuests: MainQuest[];
  archivedMainQuests: MainQuest[];

  // Recurring tasks
  recurringTasks: RecurringTask[];

  // Weekly goals
  weeklyGoals: WeeklyGoal[];
  archivedWeeklyGoals: WeeklyGoal[];

  // Habits
  habits: Habit[];
  archivedHabits: Habit[];

  // Progress logs
  progressLog: Array<{
    date: string;
    tasks: number;
    experience: number;
  }>;
  taskLogs: TaskLog[];

  // Skills
  skills: Skills;
  beliefSystem: BeliefSystemConfig;
  loreProfile: LoreProfile;
  worldState: WorldState;
  progressionConfig: ProgressionConfig;
  titleCatalog: TitleCatalog;
  orchestrationLog: OrchestrationLogEntry[];

  // Pomodoro
  pomodoro: PomodoroData;

  // Events
  events: GameEvent[];
  eventMemories: EventMemories;

  // AI analysis
  aiAnalysisHistory: AIAnalysisEntry[];

  // Resources
  resources: Resources;
  financialRecords: FinancialRecord[];
  resourceLogs: ResourceLog[];
  rewardActionLogs: RewardActionLog[];
  dailyCompletionSnapshots: Record<string, DailyCompletionSnapshot>;
  energyHistory: EnergyHistoryEntry[];

  // Journals
  journals: JournalEntry[];

  // Saved rewards
  savedRewards: SavedRewards;
  rewardPool: RewardSticker[];
  rewardPricing: RewardPricingConfig;

  // Season system
  currentSeason: Season | null; // Deprecated, kept for compatibility
  activeSeasons: Season[];
  seasonHistory: Season[];
  categories: Category[];
  transmigration: Transmigration;

  // Monitor
  monitor: MonitorSettings;

  // Questionnaire
  questionnaires: QuestionnaireHistory;
}

/**
 * Default values for initialization
 */
export const DEFAULT_STATS: PlayerStats = {
  life: 75,
  intelligence: 95,
  spirit: 95,
  action: 75,
  agility: 50,
  charm: 70,
};

export const DEFAULT_DAILY_TASKS: DailyTasks = {
  shutdown: false,
  laugh: false,
  vision: false,
  walk: false,
  signal: false,
  log: false,
};

export const DEFAULT_CATEGORIES: Category[] = [
  { id: 'work', name: '工作', icon: '💼', color: '#3b82f6' },
  { id: 'study', name: '学习', icon: '📚', color: '#10b981' },
  { id: 'life', name: '生活', icon: '🏠', color: '#f59e0b' },
  { id: 'health', name: '健康', icon: '💪', color: '#ef4444' },
  { id: 'hobby', name: '兴趣', icon: '🎨', color: '#8b5cf6' },
];
